name: Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-14
    strategy:
      matrix:
        platform: [iOS, macOS]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: Display Xcode Version
        run: xcodebuild -version

      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '6.0'

      - name: Cache Ruby gems
        uses: actions/cache@v3
        with:
          path: /usr/local/lib/ruby/gems
          key: ${{ runner.os }}-ruby-gems

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Display Swift Version
        run: swift --version

      - name: Build
        run: swift build

      - name: Run Tests (${{ matrix.platform }})
        run: |
          if [ "${{ matrix.platform }}" == "iOS" ]; then
            xcodebuild test \
              -scheme NnReminderKit \
              -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.3.1' \
              | xcpretty
          else
            xcodebuild test \
              -scheme NnReminderKit \
              -destination 'platform=macOS,arch=arm64' \
              | xcpretty
          fi
